import type { Place } from './types';

export const PLACES: Place[] = [
  // ───────────────────────────── CITIES ─────────────────────────────
  {
    id: 'melbourne',
    name: 'Melbourne',
    aliases: ['melb', 'melbs'],
    lat: -37.8136,
    lng: 144.9631,
    tier: 'city',
    region: 'Metro',
    hints: [
      "It's the capital city of Victoria",
      'It sits on the Yarra River near Port Phillip Bay',
      'Its central grid was laid out by Robert Hoddle in 1837',
    ],
  },
  {
    id: 'geelong',
    name: 'Geelong',
    lat: -38.1475,
    lng: 144.3617,
    tier: 'city',
    region: 'Barwon',
    hints: [
      "It's Victoria's second-largest city",
      'It sits on Corio Bay west of Melbourne',
      "It's home to the Cats AFL team and Ford's original Australian factory",
    ],
  },
  {
    id: 'ballarat',
    name: 'Ballarat',
    lat: -37.5622,
    lng: 143.8498,
    tier: 'city',
    region: 'Central Highlands',
    hints: [
      "It was at the centre of the 1854 gold rush Eureka Rebellion",
      "It's about 100km west-northwest of Melbourne",
      'Sovereign Hill is a major tourist attraction here',
    ],
  },
  {
    id: 'bendigo',
    name: 'Bendigo',
    lat: -36.7578,
    lng: 144.2805,
    tier: 'city',
    region: 'Loddon',
    hints: [
      'It grew rich on gold in the 1850s',
      "It's in central Victoria, north of Melbourne",
      "Its heritage trams still run through the city centre",
    ],
  },
  {
    id: 'mildura',
    name: 'Mildura',
    lat: -34.1848,
    lng: 142.1623,
    tier: 'city',
    region: 'Mallee',
    hints: [
      "It's on the Murray River in the far northwest",
      'Irrigation made it a major citrus and grape growing hub',
      'The Chaffey brothers established its irrigation scheme in the 1880s',
    ],
  },
  {
    id: 'shepparton',
    name: 'Shepparton',
    lat: -36.3801,
    lng: 145.3972,
    tier: 'city',
    region: 'Goulburn Valley',
    hints: [
      'It sits on the Goulburn River in the north',
      'Canned fruit and SPC are associated with this city',
      'A large mural of cows lines its main street',
    ],
  },
  {
    id: 'warrnambool',
    name: 'Warrnambool',
    lat: -38.3845,
    lng: 142.4805,
    tier: 'city',
    region: 'Great South Coast',
    hints: [
      "It's on the southwest coast near the Twelve Apostles",
      "Right whales calve near here in winter",
      'It started as a whaling station in the 1830s',
    ],
  },
  {
    id: 'traralgon',
    name: 'Traralgon',
    lat: -38.1975,
    lng: 146.8206,
    tier: 'city',
    region: 'Gippsland',
    hints: [
      "It's in the Latrobe Valley in Gippsland",
      'Power stations and brown coal mining dominate the region',
      'Its name comes from a Gunai/Kurnai word for "little fish"',
    ],
  },
  {
    id: 'wangaratta',
    name: 'Wangaratta',
    lat: -36.3895,
    lng: 146.3086,
    tier: 'city',
    region: 'Ovens & Murray',
    hints: [
      "It's at the junction of the Ovens and King rivers",
      'It hosts a major jazz festival each November',
      "Ned Kelly's final stand at Glenrowan is just down the road",
    ],
  },
  {
    id: 'horsham',
    name: 'Horsham',
    lat: -36.7139,
    lng: 142.2004,
    tier: 'city',
    region: 'Wimmera',
    hints: [
      "It's in the Wimmera, west of Bendigo",
      'Wheat farming dominates the surrounding area',
      "Nearby Mount Arapiles is a world-famous rock-climbing site",
    ],
  },
  {
    id: 'echuca',
    name: 'Echuca',
    lat: -36.1491,
    lng: 144.7487,
    tier: 'city',
    region: 'Murray',
    hints: [
      "It's a Murray River port town",
      'Paddlesteamers were its lifeblood in the 19th century',
      "It's right across the river from Moama in NSW",
    ],
  },
  {
    id: 'sale',
    name: 'Sale',
    lat: -38.1027,
    lng: 147.0683,
    tier: 'city',
    region: 'Gippsland',
    hints: [
      "It's in Wellington Shire, east Gippsland",
      'The Wellington Canal is here',
      'It sits on the Thomson River near its outlet to Lake Wellington',
    ],
  },

  // ───────────────────────────── SUBURBS ─────────────────────────────
  {
    id: 'footscray',
    name: 'Footscray',
    lat: -37.7991,
    lng: 144.8991,
    tier: 'suburb',
    region: 'Melbourne West',
    hints: [
      "It's a western Melbourne suburb on the Maribyrnong",
      'Famous for its multicultural food markets',
      'The Western Bulldogs AFL team calls it home',
    ],
  },
  {
    id: 'frankston',
    name: 'Frankston',
    lat: -38.1408,
    lng: 145.3892,
    tier: 'suburb',
    region: 'Melbourne South',
    hints: [
      "It's on Port Phillip Bay, southeast of the CBD",
      "It anchors the southeastern suburban rail line",
      "Locals sometimes call it the 'Gateway to the Mornington Peninsula'",
    ],
  },
  {
    id: 'dandenong',
    name: 'Dandenong',
    lat: -37.9877,
    lng: 145.2089,
    tier: 'suburb',
    region: 'Melbourne South-East',
    hints: [
      "It's southeast of the CBD, on the Princes Highway",
      'It is a major industrial and transport hub',
      "Nearby are the Dandenong Ranges (separate question)",
    ],
  },
  {
    id: 'williamstown',
    name: 'Williamstown',
    lat: -37.8566,
    lng: 144.8948,
    tier: 'suburb',
    region: 'Melbourne West',
    hints: [
      "It's on a peninsula at the mouth of the Yarra",
      'It is the oldest continuous settlement on Port Phillip',
      'Time Out Market there overlooks the bay with city skyline views',
    ],
  },
  {
    id: 'fitzroy',
    name: 'Fitzroy',
    lat: -37.7976,
    lng: 144.9793,
    tier: 'suburb',
    region: 'Melbourne Inner North',
    hints: [
      "It's the oldest suburb of Melbourne",
      "Brunswick Street is its famous drag",
      'It was the first Victorian working-class suburb',
    ],
  },
  {
    id: 'stkilda',
    name: 'St Kilda',
    lat: -37.8675,
    lng: 144.9763,
    tier: 'suburb',
    region: 'Melbourne South',
    hints: [
      'It has a famous beach and amusement park',
      'Acland Street is famous for its cake shops',
      'The Esplanade Hotel (the Espy) is a landmark here',
    ],
  },
  {
    id: 'carlton',
    name: 'Carlton',
    lat: -37.8017,
    lng: 144.9718,
    tier: 'suburb',
    region: 'Melbourne Inner North',
    hints: [
      "It's famous for Italian food on Lygon Street",
      "The Melbourne Museum and Royal Exhibition Building are here",
      'Curtin House was once a workers co-op here',
    ],
  },
  {
    id: 'brunswick',
    name: 'Brunswick',
    lat: -37.7671,
    lng: 144.9565,
    tier: 'suburb',
    region: 'Melbourne Inner North',
    hints: [
      'Sydney Road is its main drag',
      'It has a strong Middle Eastern food scene',
      'It borders Coburg to the north',
    ],
  },
  {
    id: 'richmond',
    name: 'Richmond',
    lat: -37.8183,
    lng: 144.9974,
    tier: 'suburb',
    region: 'Melbourne Inner East',
    hints: [
      "It's known for its Vietnamese food on Victoria Street",
      'The MCG and Melbourne Cricket Club are adjacent',
      'It was an industrial area of factories and breweries',
    ],
  },
  {
    id: 'camberwell',
    name: 'Camberwell',
    lat: -37.8320,
    lng: 145.0586,
    tier: 'suburb',
    region: 'Melbourne Inner East',
    hints: [
      "It's an older leafy eastern suburb",
      'The Rivoli Cinema is a landmark here',
      'It is in the City of Boroondara',
    ],
  },
  {
    id: 'coburg',
    name: 'Coburg',
    lat: -37.7399,
    lng: 144.9621,
    tier: 'suburb',
    region: 'Melbourne Inner North',
    hints: [
      'Sydney Road continues north into it from Brunswick',
      "It's famous for Lebanese food",
      'Pentridge Prison was its famous landmark',
    ],
  },
  {
    id: 'hawthorn',
    name: 'Hawthorn',
    lat: -37.8233,
    lng: 145.0386,
    tier: 'suburb',
    region: 'Melbourne Inner East',
    hints: [
      'It is in the City of Boroondara',
      'Glenferrie Road is its main shopping strip',
      'Swinburne University is based here',
    ],
  },

  // ───────────────────────────── REGIONS ─────────────────────────────
  {
    id: 'gippsland',
    name: 'Gippsland',
    lat: -37.7694,
    lng: 146.9371,
    tier: 'region',
    region: 'Gippsland',
    hints: [
      "It's the big southeastern region of Victoria",
      'Brown coal power stations dot its Latrobe Valley',
      'It extends from the Dividing Range down to the Ninety Mile Beach',
    ],
  },
  {
    id: 'mallee',
    name: 'The Mallee',
    aliases: ['mallee'],
    lat: -35.0833,
    lng: 142.0,
    tier: 'region',
    region: 'Mallee',
    hints: [
      "It's the dry, sandy northwest corner of the state",
      'Mallee scrub (eucalypt dumosa) gives it its name',
      'Mildura is its biggest town',
    ],
  },
  {
    id: 'grampians',
    name: 'Grampians',
    aliases: ['gariwerd', 'grampians national park'],
    lat: -37.2329,
    lng: 142.4660,
    tier: 'region',
    region: 'Wimmera',
    hints: [
      "It's a sandstone mountain range in western Victoria",
      "It's known to Traditional Owners as Gariwerd",
      'Halls Gap is the main tourist village inside it',
    ],
  },
  {
    id: 'mornington-peninsula',
    name: 'Mornington Peninsula',
    lat: -38.3675,
    lng: 144.9934,
    tier: 'region',
    region: 'Metro',
    hints: [
      "It separates Port Phillip from Bass Strait",
      "Sorrento and Portsea are at its tip",
      "It's a popular summer holiday and winery area",
    ],
  },
  {
    id: 'yarra-valley',
    name: 'Yarra Valley',
    lat: -37.7739,
    lng: 145.4706,
    tier: 'region',
    region: 'Yarra Ranges',
    hints: [
      'It is east of Melbourne along the Yarra River',
      'It is one of Victoria\u2019s main wine regions',
      'Healesville Sanctuary is located here',
    ],
  },
  {
    id: 'goulburn-valley',
    name: 'Goulburn Valley',
    lat: -36.4,
    lng: 145.4,
    tier: 'region',
    region: 'Goulburn Valley',
    hints: [
      "It is the irrigation heart of northern Victoria",
      'It produces most of Victoria\u2019s canned fruit',
      'Shepparton is its main city',
    ],
  },
  {
    id: 'otway-ranges',
    name: 'Otway Ranges',
    aliases: ['otways', 'great otway national park'],
    lat: -38.6833,
    lng: 143.5,
    tier: 'region',
    region: 'Great Ocean Road',
    hints: [
      "It is the rainforest range inland from the Great Ocean Road",
      'The Twelve Apostles are just off its coast',
      'Lighthouses at Cape Otway mark its southern tip',
    ],
  },
  {
    id: 'wilsons-promontory',
    name: 'Wilsons Promontory',
    aliases: ['the prom', 'wilsons prom'],
    lat: -39.0,
    lng: 146.3,
    tier: 'region',
    region: 'South Gippsland',
    hints: [
      'It is the southernmost point of mainland Australia',
      "It is a national park full of granite peaks",
      "Tidal River is its main campground",
    ],
  },
  {
    id: 'dandenong-ranges',
    name: 'Dandenong Ranges',
    aliases: ['the dandenongs'],
    lat: -37.85,
    lng: 145.35,
    tier: 'region',
    region: 'Melbourne East',
    hints: [
      "They are a cool-climate mountain range just east of Melbourne",
      'Mountain ash and tree ferns dominate the forest',
      'Puffing Billy steam train runs along its eastern edge',
    ],
  },
  {
    id: 'high-country',
    name: 'Victorian High Country',
    aliases: ['high country', 'alpine region'],
    lat: -36.85,
    lng: 147.3,
    tier: 'region',
    region: 'Alpine',
    hints: [
      'It is the alpine region of northeast Victoria',
      "Falls Creek, Mt Hotham and Mt Buller ski resorts are here",
      "It is cattle mustering (mountain cattlemen) country",
    ],
  },
  {
    id: 'wimmera',
    name: 'Wimmera',
    lat: -36.5,
    lng: 142.0,
    tier: 'region',
    region: 'Wimmera',
    hints: [
      "It is the dry western farming region of the state",
      'Wheat and barley dominate its agriculture',
      'The Grampians sit at its southern edge',
    ],
  },
  {
    id: 'loddon',
    name: 'Loddon Mallee',
    aliases: ['loddon'],
    lat: -36.5,
    lng: 143.5,
    tier: 'region',
    region: 'Loddon',
    hints: [
      "It covers the north-central part of Victoria",
      'Bendigo is its main city',
      'It spans from the Murray down toward the Dividing Range',
    ],
  },

  // ───────────────────────────── SMALL TOWNS ─────────────────────────────
  {
    id: 'beechworth',
    name: 'Beechworth',
    lat: -36.3587,
    lng: 146.7186,
    tier: 'smalltown',
    region: 'Indigo',
    hints: [
      "It's a gold-rush town in northeast Victoria",
      'Its historic bakery is famous for its pies',
      "Ned Kelly was held in its old gaol",
    ],
  },
  {
    id: 'port-fairy',
    name: 'Port Fairy',
    lat: -38.3488,
    lng: 142.5465,
    tier: 'smalltown',
    region: 'Moyne',
    hints: [
      "It's a coastal town west of Warrnambool",
      'It started as a whaling and sealing port',
      'Its folk music festival is nationally known',
    ],
  },
  {
    id: 'maldon',
    name: 'Maldon',
    lat: -36.9587,
    lng: 144.0506,
    tier: 'smalltown',
    region: 'Mount Alexander',
    hints: [
      "It's a gold-rush town near Castlemaine",
      "It's Victoria's first notable town (National Trust)",
      'A heritage steam railway runs from here',
    ],
  },
  {
    id: 'heathcote',
    name: 'Heathcote',
    lat: -36.9189,
    lng: 144.7119,
    tier: 'smalltown',
    region: 'City of Greater Bendigo',
    hints: [
      "It's between Bendigo and Melbourne on the Northern Highway",
      'It sits on a famous belt of Cambrian rocks',
      'Its Shiraz vines are known as "Heathcote Shiraz"',
    ],
  },
  {
    id: 'korumburra',
    name: 'Korumburra',
    lat: -38.4301,
    lng: 145.8211,
    tier: 'smalltown',
    region: 'South Gippsland',
    hints: [
      "It's in the rolling green hills of South Gippsland",
      'Coal was mined here in the early 1900s',
      'A giant spud statue greets visitors',
    ],
  },
  {
    id: 'swifts-creek',
    name: 'Swifts Creek',
    lat: -37.0277,
    lng: 147.4959,
    tier: 'smalltown',
    region: 'Alpine',
    hints: [
      'It is a small town in East Gippsland',
      "It is in the Tambo River valley",
      'It was a mining and timber town',
    ],
  },
  {
    id: 'harrow',
    name: 'Harrow',
    lat: -37.0833,
    lng: 141.3,
    tier: 'smalltown',
    region: 'Glenelg',
    hints: [
      "It is a tiny town in the far west of the state",
      "It is near the South Australian border",
      'The Glenelg River flows nearby',
    ],
  },
  {
    id: 'tarnagulla',
    name: 'Tarnagulla',
    lat: -36.75,
    lng: 143.5,
    tier: 'smalltown',
    region: 'Loddon',
    hints: [
      "It is a gold-rush ghost town in central Victoria",
      "It is south of Inglewood",
      'Once known as Sandy Creek',
    ],
  },
  {
    id: 'walhalla',
    name: 'Walhalla',
    lat: -37.9333,
    lng: 146.45,
    tier: 'smalltown',
    region: 'Baw Baw',
    hints: [
      'It is a tiny gold-rush town in Gippsland',
      "It sits in a narrow valley on Stringers Creek",
      'A tourist railway runs to it from Thomson',
    ],
  },
  {
    id: 'clunes',
    name: 'Clunes',
    lat: -37.7861,
    lng: 143.7886,
    tier: 'smalltown',
    region: 'Hepburn',
    hints: [
      "It's a gold-rush town north of Ballarat",
      "It hosts an annual Booktown festival",
      'Much of the film "Mad Max" was shot nearby',
    ],
  },
  {
    id: 'sorrento',
    name: 'Sorrento',
    lat: -38.3393,
    lng: 144.7519,
    tier: 'smalltown',
    region: 'Mornington Peninsula',
    hints: [
      "It's at the tip of the Mornington Peninsula",
      "It has front and back beaches on either side",
      "A car ferry runs from here to Queenscliff",
    ],
  },
  {
    id: 'queenscliff',
    name: 'Queenscliff',
    lat: -38.2725,
    lng: 144.6637,
    tier: 'smalltown',
    region: 'Bellarine',
    hints: [
      "It's at the western tip of the Bellarine Peninsula",
      'It guards the entrance to Port Phillip',
      'A car ferry runs from here to Sorrento',
    ],
  },
  {
    id: 'castlemaine',
    name: 'Castlemaine',
    lat: -37.0646,
    lng: 144.2147,
    tier: 'smalltown',
    region: 'Mount Alexander',
    hints: [
      "It's a gold-rush town on the Loddon River",
      'Diggers began the Mount Alexander rush here in 1851',
      'It is between Bendigo and Ballarat',
    ],
  },
  {
    id: 'daylesford',
    name: 'Daylesford',
    lat: -37.3,
    lng: 144.15,
    tier: 'smalltown',
    region: 'Hepburn',
    hints: [
      'It is on the Wombat Plateau in central Victoria',
      'It is famous for mineral springs and spas',
      'It is a major tourism town for wellness retreats',
    ],
  },
];

export function placesByTier(tier: import('./types').Tier): Place[] {
  return PLACES.filter((p) => p.tier === tier);
}
